from __future__ import annotations

"""Retrieval 层默认常量。"""

DEFAULT_TOP_K = 5
DEFAULT_CANDIDATE_MULTIPLIER = 4
DEFAULT_RRF_K = 60

DEFAULT_ENABLE_QUERY_REWRITE = True
DEFAULT_ENABLE_HYBRID = True
DEFAULT_ENABLE_RERANK = True

DEFAULT_SORT_BY = "distance"
DEFAULT_ADAPTIVE_FALLBACK_FLOOR = 0.45

# Rule rerank 默认权重
DEFAULT_RERANK_VECTOR_WEIGHT = 0.72
DEFAULT_RERANK_KEYWORD_WEIGHT = 0.18
DEFAULT_RERANK_RECENCY_WEIGHT = 0.10
DEFAULT_RERANK_CANONICAL_FACT_BOOST = 0.03
DEFAULT_RERANK_BACKEND = "rule"
DEFAULT_CROSS_ENCODER_TIMEOUT = 8.0
DEFAULT_AB_TEST_ENABLED = True
DEFAULT_AB_TEST_B_RATIO = 0.5

# Hybrid RRF 默认权重
DEFAULT_HYBRID_VECTOR_WEIGHT = 1.0
DEFAULT_HYBRID_KEYWORD_WEIGHT = 0.7

# Vector backend
DEFAULT_VECTOR_BACKEND = "pgvector"
DEFAULT_VECTOR_DIM = 1024
DEFAULT_FAISS_METRIC = "cosine"
DEFAULT_MILVUS_URI = "http://127.0.0.1:19530"
DEFAULT_MILVUS_COLLECTION = "writer_memory_chunks"
DEFAULT_QDRANT_URL = "http://127.0.0.1:6333"
DEFAULT_QDRANT_COLLECTION = "writer_memory_chunks"
