"""init tables

Revision ID: c98141f97df1
Revises: 
Create Date: 2026-03-29 04:37:04.738017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import UserDefinedType

# revision identifiers, used by Alembic.
revision: str = 'c98141f97df1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class PgVector1536(UserDefinedType):
    """迁移内联的 vector(1536)，避免依赖包路径。"""

    cache_ok = True

    def get_col_spec(self, **kw: object) -> str:
        return "vector(1536)"


def upgrade() -> None:
    """Upgrade schema."""
    # 先于建表创建 ENUM；已存在时不报错，建表侧使用 create_type=False 避免重复 CREATE TYPE。
    for stmt in (
        "DO $$ BEGIN CREATE TYPE agent_run_status_enum AS ENUM "
        "('pending', 'running', 'success', 'failed'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
        "DO $$ BEGIN CREATE TYPE skillrun_status_enum AS ENUM "
        "('pending', 'running', 'success', 'failed'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
        "DO $$ BEGIN CREATE TYPE toolcall_status_enum AS ENUM "
        "('pending', 'running', 'success', 'failed'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
        "DO $$ BEGIN CREATE TYPE chapter_status_enum AS ENUM ('draft', 'published'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
        "DO $$ BEGIN CREATE TYPE foreshadowing_status_enum AS ENUM ('open', 'resolved'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
        "DO $$ BEGIN CREATE TYPE embedding_status_enum AS ENUM "
        "('pending', 'processing', 'done', 'failed'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
    ):
        op.execute(sa.text(stmt))

    # 启用 pgvector，否则不存在 ``vector`` 类型，``memory_chunks.embedding`` 会报错。
    # 要求 PostgreSQL 实例已安装 pgvector（例如镜像 ``pgvector/pgvector:pg16``）。
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'success', 'failed', name='agent_run_status_enum', create_type=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_input_json', 'agent_runs', ['input_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_agent_output_json', 'agent_runs', ['output_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_agent_project', 'agent_runs', ['project_id'], unique=False)
    op.create_index('idx_agent_request', 'agent_runs', ['request_id'], unique=False)
    op.create_index('idx_agent_status', 'agent_runs', ['status'], unique=False)
    op.create_index('idx_agent_trace', 'agent_runs', ['trace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('premise', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('skill_name', sa.Text(), nullable=True),
    sa.Column('skill_version', sa.Text(), nullable=True),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'success', 'failed', name='skillrun_status_enum', create_type=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skillruns_agent_run', 'skill_runs', ['agent_run_id'], unique=False)
    op.create_index('idx_skillruns_status', 'skill_runs', ['status'], unique=False)
    op.create_index('idx_skillruns_trace', 'skill_runs', ['trace_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'success', 'failed', name='toolcall_status_enum', create_type=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_toolcalls_agent_run', 'tool_calls', ['agent_run_id'], unique=False)
    op.create_index('idx_toolcalls_status', 'tool_calls', ['status'], unique=False)
    op.create_index('idx_toolcalls_trace', 'tool_calls', ['trace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'published', name='chapter_status_enum', create_type=False), server_default='draft', nullable=False),
    sa.Column('draft_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_no', name='uq_chapters_project_id_chapter_no')
    )
    op.create_index('idx_chapters_project', 'chapters', ['project_id'], unique=False)
    op.create_index('idx_chapters_status', 'chapters', ['status'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role_type', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('faction', sa.Text(), nullable=True),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('speech_style_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('arc_status_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_characters_project', 'characters', ['project_id'], unique=False)
    op.create_table('foreshadowings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('setup_chapter_no', sa.Integer(), nullable=True),
    sa.Column('setup_text', sa.Text(), nullable=True),
    sa.Column('expected_payoff', sa.Text(), nullable=True),
    sa.Column('payoff_chapter_no', sa.Integer(), nullable=True),
    sa.Column('payoff_text', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'resolved', name='foreshadowing_status_enum', create_type=False), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_foreshadowings_project', 'foreshadowings', ['project_id'], unique=False)
    op.create_index('idx_foreshadowings_status', 'foreshadowings', ['status'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding_status', postgresql.ENUM('pending', 'processing', 'done', 'failed', name='embedding_status_enum', create_type=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('embedding', PgVector1536(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_metadata', 'memory_chunks', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_chunks_project', 'memory_chunks', ['project_id'], unique=False)
    op.create_index('idx_chunks_source', 'memory_chunks', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_embedding', 'memory_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.Text(), nullable=True),
    sa.Column('event_desc', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('involved_characters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('causal_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timeline_project', 'timeline_events', ['project_id'], unique=False)
    op.create_table('world_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worldentries_entry_type', 'world_entries', ['entry_type'], unique=False)
    op.create_index('idx_worldentries_project', 'world_entries', ['project_id'], unique=False)
    op.create_table('chapter_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_agent', sa.Text(), nullable=True),
    sa.Column('source_workflow', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'version_no', name='uq_chapter_versions_chapter_id_version_no')
    )
    op.create_index('idx_chapter_versions_chapter_id', 'chapter_versions', ['chapter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chapter_versions_chapter_id', table_name='chapter_versions')
    op.drop_table('chapter_versions')
    op.drop_index('idx_worldentries_project', table_name='world_entries')
    op.drop_index('idx_worldentries_entry_type', table_name='world_entries')
    op.drop_table('world_entries')
    op.drop_index('idx_timeline_project', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('idx_embedding', table_name='memory_chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_chunks_source', table_name='memory_chunks')
    op.drop_index('idx_chunks_project', table_name='memory_chunks')
    op.drop_index('idx_chunks_metadata', table_name='memory_chunks', postgresql_using='gin')
    op.drop_table('memory_chunks')
    op.drop_index('idx_foreshadowings_status', table_name='foreshadowings')
    op.drop_index('idx_foreshadowings_project', table_name='foreshadowings')
    op.drop_table('foreshadowings')
    op.drop_index('idx_characters_project', table_name='characters')
    op.drop_table('characters')
    op.drop_index('idx_chapters_status', table_name='chapters')
    op.drop_index('idx_chapters_project', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_toolcalls_trace', table_name='tool_calls')
    op.drop_index('idx_toolcalls_status', table_name='tool_calls')
    op.drop_index('idx_toolcalls_agent_run', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('idx_skillruns_trace', table_name='skill_runs')
    op.drop_index('idx_skillruns_status', table_name='skill_runs')
    op.drop_index('idx_skillruns_agent_run', table_name='skill_runs')
    op.drop_table('skill_runs')
    op.drop_table('projects')
    op.drop_index('idx_agent_trace', table_name='agent_runs')
    op.drop_index('idx_agent_status', table_name='agent_runs')
    op.drop_index('idx_agent_request', table_name='agent_runs')
    op.drop_index('idx_agent_project', table_name='agent_runs')
    op.drop_index('idx_agent_output_json', table_name='agent_runs', postgresql_using='gin')
    op.drop_index('idx_agent_input_json', table_name='agent_runs', postgresql_using='gin')
    op.drop_table('agent_runs')
    for typ in (
        'embedding_status_enum',
        'foreshadowing_status_enum',
        'chapter_status_enum',
        'toolcall_status_enum',
        'skillrun_status_enum',
        'agent_run_status_enum',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {typ} CASCADE'))
    op.execute(sa.text("DROP EXTENSION IF EXISTS vector"))
    # ### end Alembic commands ###
